# Generated by Django 4.2 on 2024-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_user_is_active', 'Can change user is active'), ('view_users', 'Can view Users')]},
        ),
    ]
