# Generated by Django 4.2 on 2024-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailingsettings_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='mailings.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='last_send',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней отправки'),
        ),
    ]
