# Generated by Django 4.2 on 2024-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailingsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема рассылки'),
        ),
    ]
