# Generated by Django 4.2 on 2024-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_mailingsettings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='mailings/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mailings/', verbose_name='Изображение'),
        ),
    ]
