# Generated by Django 4.2 on 2024-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0009_remove_message_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='message',
            field=models.ManyToManyField(to='mailings.message', verbose_name='Сообщения'),
        ),
    ]
