# Generated by Django 4.2 on 2024-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0010_mailingsettings_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='last_send',
            field=models.DateTimeField(verbose_name='Дата последней отправки'),
        ),
    ]
