# Generated by Django 4.2 on 2024-05-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0012_remove_mailingsettings_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала рассылки'),
        ),
    ]
