# Generated by Django 4.2 on 2024-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0021_alter_client_owner_alter_log_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('view_any_mailings', 'Can view any mailings'), ('change_mailing_is_active', 'Can change mailing is active')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
